

#ifndef MESSAGEERRORS_H_
#define MESSAGEERRORS_H_

#include "../../utils/Config.h"

namespace dpi {

enum MessageErrors
  : unsigned int {

  NO_ERROR = 0,
  INVALID_MESSAGE,  // make use of auto-increment

  MEMORY_NOT_AVAILABLE = 100,
  MEMORY_RELEASE_FAILED,

  DB_LOAD_DATA_FAILED = 200,
  DB_SN_NODE_NOT_AVAILABLE,

  SSB_INVALID_COMMAND = 300,

  DB_CREATE_TABLE_FAILED = 400,
  DB_RESTORE_SNAPSHOT_FAILED = 401,
  DB_TAKE_SNAPSHOT_FAILED = 402,
  DB_STORAGE_PARTITIONS_NOTEQUAL = 403,
  DB_CLASSIC_HASH_EXTRA_ATTR = 404,

  DPI_CREATE_RING_ON_BUF_FAILED = 500,
  DPI_RTRV_BUFFHANDLE_FAILED = 501,
  DPI_APPEND_BUFFHANDLE_FAILED = 502,
  DPI_JOIN_BUFFER_FAILED = 503
};

}

#endif /* MESSAGEERRORS_H_ */
